# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20)),
                ('commentType', models.CharField(max_length=10)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTag', models.CharField(max_length=20)),
                ('filePath', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgComment.Image'),
        ),
    ]
