# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgComment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filePath',
        ),
        migrations.AddField(
            model_name='image',
            name='editFile',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='origFile',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentType',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='postTag',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
