# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgComment', '0003_auto_20151226_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
